### ISSUE TITLE
Is there a way to output fchk of salc?

### ISSUE THREAD

**Issue by vladislavivanistsev** [mcodev31/libmsym#10]
The library gives coefficients for the salc. I am looking for a way to visualize them. It seems to be impossible or tricky with Avogadro or Luscus. Is there a way to output fchk of salc using the libmsym library?

**Comment by mcodev31** [comment]
In order to visualise them you need need integral/overlap matrixes for the basis set you are using.
Since the symmetry of the overlap is the same as the overall symmetry, and the radial part of the basis function isn't relevant libmsym does not need this info (you do however need to take it into account for any calculations). Molpy (https://github.com/steabert/molpy) uses the Fock_int and overlap data from Molcas (http://www.molcas.org) to get this data, and can generate guess orbitals using libmsym. In theory Avogadro could visualise something directly, using predefined basis sets (this is something I've considered implementing), but it's not possible right now.
Edit:
Molcas can also generate symmetric output using libmsym that can be imported into Luscus.

**Comment by vladislavivanistsev** [comment]
Thank you for answering. I hope you would implement this feature in Avogadro.

**Comment by ghutchis** [comment]
Either way - I'd be happy to help get parts of this working in `avogadrolibs` - it doesn't seem like it would be hard to add a "symmetrize MO" feature if `libmsym` is giving the SALC coefficients because we already have the Gaussian basis.
