### ISSUE TITLE
Is there any document or manual to instruct me how to use the library?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [mcodev31/libmsym#22]
Hello everyone. I am a student who want to implement `libmsym` in my code. In this webpage I do not see any tutorial to use to learn how to use this library, except the `examples` code, which is not commented enough for me to understand. I wonder if there is any document or manual or wiki that I can resort to, like what `libint2` has.

**Comment by FreemanTheMaverick** [comment]
Well. There are no answers, so I will assume that there are no learning materials of `libmsym`, so I cannot utilize it in my code, and I will have to write a molecular symmetry library of my own. Actually I have already done part of it while waiting for an answer to this issue. It is tedious, but I do not think completing it will take long.

**Comment by mcodev31** [comment]
Hi,

The difference in number of active developers between this library and libint is quite significant. There is no documentation besides the README, example code and [publication](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-017-0193-3).
If you can write your own symmetry library it shouldn't be to hard to decipher the example code (c/python). If you are just interested in finding the point group (rather than wave function symmetrization) there are several other projects that do just that.
