### ISSUE TITLE
Why the program gives the error when I use this molecular?

### ISSUE THREAD

**Issue by sherlcrow** [mcodev31/libmsym#25]
9
ethanol
 C    8.960767    9.678596   11.324902
 C   10.040371   10.373322   12.130129
 O   11.307616   10.105125   11.507543
 H    9.127848    8.591672   11.301701
 H    8.948935   10.046791   10.288465
 H    7.974955    9.869172   11.772836
 H   10.035117   10.001044   13.173151
 H    9.849029   11.463604   12.160981
 H   12.004366   10.549272   12.000293

I want to analysis an ethanol molecular point group, This is a file with the suffix '.xyz' , it was transformed by VESTA from a ethanol crystal.  When I use the program,  I accept an error that is "Error Error determining point group: Point group has no primary axis for reorientation" , I don`t know how to deal with it , I wish you can help me.

**Comment by mcodev31** [comment]
I suspect it is because it's not quite symmetrical. The example code (which I assume you are referring to) uses the rather tight default threshold and is meant as example for integration into other software (this is a library). If you use e.g. [Avogadro](https://www.openchemistry.org/projects/avogadro2/) (it uses libmsym internally) you can see that it gives C1 with a tight threshold and Cs with normal. It also allows you to symmetrize the molecule (see below). There is also be a version of [Luscus](http://luscus.sourceforge.net/) that uses libmsym where you can set all thresholds individually and generate symmetrical molecules.

Symmetrized:

```
9
ethanol
C      8.96061    9.67982   11.32405
C     10.04025   10.37424   12.12949
O     11.30778   10.10383   11.50844
H      9.13001    8.59331   11.29813
H      8.94613   10.05029   10.28847
H      7.97519    9.86734   11.77411
H     10.03416   10.00267   13.17270
H      9.84964   11.46473   12.15952
H     12.00577   10.53813   12.00802
```
