### ISSUE TITLE
Trouble finding D5 / D5d / D5h

### ISSUE THREAD

**Issue by ghutchis** [mcodev31/libmsym#4]
Here are two ferrocenes that seem to give issues finding D5\* groups.

https://www.dropbox.com/s/31566td477jk0h8/Fc-D5h.xyz?dl=0
https://www.dropbox.com/s/0iebvlz0bfjccua/Fc-D5v.xyz?dl=0

In general, it seems like the "loose" thresholds we discussed previously aren't definitely better than the "normal" ones.

**Comment by mcodev31** [comment]
Well no, the way thresholds are defined does not really mean loose is better.
Since this is not an exhaustive search algorithm what are good thresholds does depend a little on what type of molecule it is an generally the tighter the better.

The equivalence set detection algorithm is completely general for any molecule right now (since that was the topic of the project when I wrote it). It is basically a clustering algorithm for symmetry invariant properties, and so obviously a too loose threshold will make fewer clusters. It will be redesigned to handle these cases (and especially abelian groups) much better, but I’m a little pressed for time and the main focus has been to get SALC generation working (which it is!).

But I do agree that those loose thresholds are quite bad.
Unfortunately some molecules will required those kind of thresholds, but these will probably give a better result in most cases.

msym_thresholds_t loose_thresholds = {
    .zero = 0.040,
    .geometry = 0.040,
    .angle = 0.016,
    .equivalence = 0.032,
    .permutation = 0.050,
    .eigfact = 1.0e-3,
    .orthogonalization = 0.1
};

The D5d molecule is quite symmetry broken and I’m not entirely sure how to detect those mirror planes, I’ll need to think about that.

/M

**Comment by mcodev31** [comment]
It turns out that the application of the angle threshold could have been more consistent for symmetric polyherda. The latest checkin should find these easier. I'll close this now.
